version: '3.9'

services:
  mysql8:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../.env.local
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./data:/var/lib/mysql
